// <auto-generated />
namespace CustomizandoCodeFirstMigration.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AlteraTelefoneFixoERenomeiaCelularDePessoa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlteraTelefoneFixoERenomeiaCelularDePessoa));
        
        string IMigrationMetadata.Id
        {
            get { return "201802091747473_AlteraTelefoneFixoERenomeiaCelularDePessoa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
